import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode; modal: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-8/12 mx-auto">
          <header className="py-10">
            <nav className="space-x-8">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/gallery">Gallery</Link>
            </nav>
          </header>
          <main>{props.children}</main>
          {props.modal}
        </div>
      </body>
    </html>
  );
}
